FoodMenuApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as authentication_views
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='food/index.html'), name='logout'),
    path('profile/', user_views.profile_page, name='profile')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path

from . import views

app_name = 'food'
urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('item/', views.item, name='item'),
    path('<int:pk>', views.FoodDetail.as_view(), name='detail'),
    path('add', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:id>', views.update_item, name='update_item'),
    path('delete/<int:id>', views.delete_item, name='delete_item'),
]

food/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.

class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.ImageField(default='default.jpeg', upload_to='food')

    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.item_name

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pic.png', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms

from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView

from food.forms import ItemForm
from food.models import Item


# Create your views here.
# def index(request):
#     item_list = Item.objects.all()
#     context = {
#         'item_list': item_list
#     }
#     return render(request, 'food/index.html', context)


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'


class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def item(request):
    return HttpResponse('<h1>This is an item view</h1>')


# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item': item
#     }
#
#     return render(request, 'food/detail.html', context)


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form})


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form})

    return None


def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'food/item-delete.html', {'item': item})

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from users.forms import RegisterForm


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()

    return render(request, 'users/register.html', {'form': form})


@login_required
def profile_page(request):
    return render(request, 'users/profile.html')

templates/food/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>
    <div class="navbar">
        <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Item</a>
        <a href="#" class="nav-item nav-link">Delete Item</a>
        <a href="#" class="nav-item nav-link">View Item</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}" class="nav-item nav-link">Profile</a>
            <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
        {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
        {% endif %}
    </div>
</nav>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tag }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% block body %}
{% endblock %}
</body>
</html>

templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ object.item_image.url }}" alt="" class="card" width="300px">
            </div>
            <div class="col-md-6">
                <h1>{{ object.item_name }}</h1>
                <h2>{{ object.item_desc }}</h2>
                <h3>{{ object.item_price }}</h3>
                <a href="{% url 'food:delete_item' object.id %}">Delete</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/food/index.html
{% extends 'food/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

{% block body %}
    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img src="{{ item.item_image.url }}" alt="" class="card" height="150px">
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>
                <h6>{{ item.user_name }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}
</body>
</html>

templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            Add Item
                        </div>
                    </div>

                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <form method="POST">
                                {% csrf_token %}
                                {{ form }}
                                <button type="submit" class="btn-info">Add</button>
                            </form>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            Login
                        </div>
                    </div>

                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn-info">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/logout.html
<h1>You have been logged out</h1>

templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" width="100px">

templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            Register
                        </div>
                    </div>

                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <form method="POST">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">
                                        {{ field.name }}
                                        <br>
                                        {{ field }}
                                    </div>
                                {% endfor %}
                                <button type="submit" class="btn-info">Signup</button>
                            </form>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}